name: mosaic_underice_sunlight
channels:
 - conda-forge

dependencies:
 - python ~=3.10

###################################################
# Imported dependencies and extensions            #
###################################################

 - libgfortran~=3.0
 - jupyterlab
 - matplotlib
 - cartopy
 - dask
 - xarray
 - bottleneck
 - openpyxl
 - earthaccess
 - pytest
 - h5netcdf
 - kerchunk
 - fsspec
 - dask-labextension
 - cftime
 - nbdime
 - hvplot
 - geopandas
 - pip
 - pip:
   - /home/apbarret/src/seaice_radiative_transfer
