name: mosaic_underice_sunlight
channels:
 - conda-forge
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - libgfortran ~= 3.0
 - jupyterlab
 - nbdime
 - dask-labextension
 - matplotlib
 - cartopy
 - dask
 - xarray
 - h5netcdf
 - cftime
 - openpyxl
 - earthaccess
 - pytest
 - kerchunk
 - fsspec
 
